on:
  workflow_call:
    inputs:
      maas-snap-version:
        required: true
        type: string

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Setup
        env:
          MAAS_VERSION: ${{ inputs.maas-snap-version }}
        run: make prepare
      - name: Test
        run: make test
      - name: Clean
        if: always()        
        continue-on-error: true        
        run: make clean
