on:
  workflow_call:
    inputs:
      plaintext-version:
        required: true
        type: string
      maas-snap-version:
        required: true
        type: string

jobs:
  build:
    runs-on: self-hosted
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v3
      - name: Setup
        env:
          MAAS_VERSION: ${{ inputs.maas-snap-version }}
        run: make prepare
      - name: Test
        run: make test
      - name: Clean
        if: always()        
        continue-on-error: true        
        run: make clean
      - name: Update ok badge
        if: success()
        uses: schneegans/dynamic-badges-action@v1.5.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: a3112d7741968f0e37f9984d65cf4e24
          filename: ${{ inputs.plaintext-version }}.json 
          label: ${{ inputs.maas-snap-version }}
          message: ok
          color: green
      - name: Update fail badge
        if: failure() || cancelled()
        uses: schneegans/dynamic-badges-action@v1.5.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: a3112d7741968f0e37f9984d65cf4e24
          filename: ${{ inputs.plaintext-version }}.json 
          label: ${{ inputs.maas-snap-version }}
          message: fail
          color: red
