name: MAAS Matrix end 2 end tests

on:
  workflow_dispatch:

jobs:
  build_job:
    runs-on: ubuntu-22.04
    name: Build on ${{ matrix.distro }} ${{ matrix.arch }}
    strategy:
      matrix:
        include:
          - arch: aarch64
            distro: ubuntu22.04
          - arch: ppc64le
            distro: ubuntu22.04
          - arch: s390x
            distro: ubuntu22.04
          - arch: armv7
            distro: ubuntu22.04

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run on architecture
        uses: uraimo/run-on-arch-action@v2.5.1
        with:
          arch: ${{ matrix.arch }}
          distro: ${{ matrix.distro }}
          # Not required, but speeds up builds
          githubToken: ${{ github.token }}
          run: |
            chmod +x run.sh
            ./run.sh

