name: MAAS e2e on Ubuntu

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Setup
        run: make prepare
      - name: Test
        run: make test
      - name: Clean
        run: make clean
