name: MAAS e2e on Ubuntu

on:
  workflow_dispatch:

jobs:
  build:
    services:
      postgres:
        image: postgres
  
        env:
          POSTGRES_PASSWORD: maas
          POSTGRES_USER: maas
          POSTGRES_DB: maasdb
  
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup LXD
        uses: canonical/setup-lxd@v0.1.1
        with:
          channel: latest/stable
      - name: Setup and test
        run: |
          chmod +x run.sh
          ./run.sh
