name: MAAS e2e on Ubuntu

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        snap-version: ["3.3/edge", "3.4/edge", "latest/edge"]
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Setup
        env:
          MAAS_VERSION: ${{ matrix.snap-version }}
        run: make prepare
      - name: Test
        run: make test
      - name: Clean
        if: always()        
        continue-on-error: true        
        run: make clean
